### ISSUE TITLE
assert len(probabilities) == 362

### ISSUE THREAD

**Issue by gcp** [leela-zero/leela-zero#1303]
```
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/morbo/git/leela-zero/training/tf/chunkparser.py", line 300, in task
    for item in self.convert_chunkdata_to_v2(chunkdata):
  File "/home/morbo/git/leela-zero/training/tf/chunkparser.py", line 286, in convert_chunkdata_to_v2
    success, data = self.convert_v1_to_v2(str_items)
  File "/home/morbo/git/leela-zero/training/tf/chunkparser.py", line 186, in convert_v1_to_v2
    assert len(probabilities) == 362
AssertionError
Reader EOF
```

Almost certainly caused by modified clients sending corrupted data. But the parser should/ignore warn on it, not fail. @ywrt

**Comment by ywrt** [comment]
I think this assert is carried forward from the original code?

I can't think of anything better to do here than discard the record? and maybe log in some fashion.
Should a bad record result in the game being discarded? (on the basis that it's probably from a broken client).

**Comment by gcp** [comment]
I did https://github.com/gcp/leela-zero/commit/cd0d852a4f0cc93c89733a62c1791771ee31f0ec

Discarding the entire game seems good, but tricky because we shuffle before this point.

**Comment by sethtroisi** [comment]
closing older issue with no active discussion with many code changes since
