### ISSUE TITLE
Is "multi-gpus training support" in next branch only for linux?

### ISSUE THREAD

**Issue by trainewbie** [leela-zero/leela-zero#1437]
My OS is windows7(with python 3.5 or 3.6 or ananconda, tensorflow 1.4, cuda 8.0 and cudnn 6.0).
There was no problem to use net_to_model and train a network in a single gpu with the master branch tf.

When using python net_to_model.py and python parse.py command with multi-gpus tf, errors occur.
Am I missing something?

**Comment by gcp** [comment]
What errors occur?

**Comment by trainewbie** [comment]
This is the error message when using net_to_model

J:\mtraining\tf>python net_to_model.py a.txt
Version 1
Channels 256
Blocks 20
2018-05-17 02:58:29.349474: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that th
is TensorFlow binary was not compiled to use: AVX AVX2
2018-05-17 02:58:29.861504: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:01:00.0
totalMemory: 11.00GiB freeMemory: 10.72GiB
2018-05-17 02:58:30.180522: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 1 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.721
pciBusID: 0000:02:00.0
totalMemory: 11.00GiB freeMemory: 10.73GiB
2018-05-17 02:58:30.196523: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Device peer to peer matrix
2018-05-17 02:58:30.203523: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1051] DMA: 0 1
2018-05-17 02:58:30.210524: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1061] 0:   Y N
2018-05-17 02:58:30.217524: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1061] 1:   N Y
2018-05-17 02:58:30.225525: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/devic
e:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute cap
ability: 6.1)
2018-05-17 02:58:30.237525: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\t
ensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/devic
e:GPU:1) -> (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute cap
ability: 6.1)
Traceback (most recent call last):
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be eve
nly divisible by 4 but is 1
        Number of ways to split should evenly divide the split dimension for 'split' (op
: 'Split') with input shapes: [], [1,18,361] and with computed input tensors: input[0] =
 <0>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "net_to_model.py", line 27, in <module>
    tfprocess.init(batch_size=1)
  File "J:\mtraining\tf\tfprocess.py", line 162, in init
    self.init_net(planes, probs, winner)
  File "J:\mtraining\tf\tfprocess.py", line 166, in init_net
    self.sx = tf.split(planes, self.gpus_num)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\ops\array_ops.py", line 1265, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\ops\gen_array_ops.py", line 5093, in _split
    name=name)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Users\home\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflo
w\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size must be evenly divisible by 4 but is 1
        Number of ways to split should evenly divide the split dimension for 'split' (op
: 'Split') with input shapes: [], [1,18,361] and with computed input tensors: input[0] =
 <0>.

J:\mtraining\tf>

**Comment by godmoves** [comment]
>Number of ways to split should evenly divide the split dimension for 'split' (op
: 'Split') with input shapes: [], [1,18,361] and with computed input tensors: input[0] =
<0>.

Seems an error of split, I will check that.

**Comment by bjiyxo** [comment]
I heard that it can be solved by compiling TensorFlow. You may try it.

**Comment by godmoves** [comment]
@trainewbie This issue is something about the TensorFlow's variable assignment mechanism, and maybe soft placement will solve that. I have updated the code, can you check it?

**Comment by trainewbie** [comment]
@godmoves Solved! Great!
I didn't see any error message,
Model was created, model training by 4 gpus works well perfectly.

Thanks a lot. :-)

**Comment by godmoves** [comment]
Thanks for your feedback, I will open a PR for this :smile:
